program: src/train.py
method: grid
command:
  - ${env}
  - python3
  - ${program}
metric:
  name: val_loss
  goal: minimize

parameters:
  n_layer:
    values: [1, 2, 4]
  n_embd:
    values: [4, 8, 16]
  attn_only:
    values: [true, false]
  normalization_type:
    values: ["none", "LN"]
