model:
  name: "HookedTransformerModel"
  vocab_size: 3
  n_ctx: 4
  n_positions: 4
  d_head: 8
  n_head: 1
  n_layer: 2
  n_embd: 8
  n_inner: 16
  activation_function: "relu"
  normalization_type: null  # Use null or ~ for Python None (disables layer normalization)
  attn_only: True
  tie_word_embeddings: True

train:
  process: mess3
  batch_size: 128
  learning_rate: 0.00002
  num_epochs: 20000 # scale such that training datapoints are roughly of the same number
  device: "cuda"
  wandb_project_name: "hidden-markov-model"
  wandb_run_name: "model-mess3-ctx4-lr-2e-5-batch-64-newgen"

dataset:
  mode: "precomputed"
  path: "data/datasets/mess3_ctx4"
  eval_interval: 1000

scheduler:
  type: "none"  # Options: "cosine", "step", "exponential", "plateau", "warmup_cosine", "none"
  min_lr: 0.000001  # For cosine annealing
  warmup_epochs: 1000  # For warmup_cosine
  step_size: 5000  # For step scheduler
  gamma: 0.5  # For step/exponential schedulers
  patience: 1000  # For plateau scheduler
  factor: 0.5  # For plateau scheduler