#!/usr/bin/env python3
"""
Metadata Utilities - Convenience functions for querying training run metadata

This module provides helper functions for loading and querying the metadata.parquet
file generated by metadata_builder.py.

Example usage:
    from metadata_utils import load_metadata, query_metadata, get_best_runs

    # Load metadata
    df = load_metadata()

    # Query specific runs
    mess3_runs = query_metadata(process='mess3', status='completed')

    # Get best performing runs
    best = get_best_runs(n=10, metric='min_val_loss')

    # Get sweep summary
    sweep_info = get_sweep_summary('2025-12-09 01:03:57')
"""

import pandas as pd
from pathlib import Path
from typing import Optional, Dict, List, Union


def load_metadata(path: Optional[Path] = None) -> pd.DataFrame:
    """
    Load metadata DataFrame.

    Args:
        path: Path to metadata file (default: records/metadata.parquet)

    Returns:
        DataFrame with metadata for all runs

    Raises:
        FileNotFoundError: If metadata file doesn't exist
    """
    if path is None:
        path = Path(__file__).parent / "records" / "metadata.parquet"

    if not path.exists():
        raise FileNotFoundError(
            f"Metadata not found: {path}\n"
            f"Run: python metadata_builder.py --rebuild"
        )

    return pd.read_parquet(path)


def query_metadata(
    path: Optional[Path] = None,
    **filters
) -> pd.DataFrame:
    """
    Query metadata with filters.

    Args:
        path: Path to metadata file (optional)
        **filters: Column filters as key=value pairs

    Returns:
        Filtered DataFrame

    Examples:
        # Get all completed mess3 runs
        query_metadata(process='mess3', status='completed')

        # Get all 4-layer models
        query_metadata(n_layer=4)

        # Get all sweep runs
        query_metadata(is_sweep=True)
    """
    df = load_metadata(path)

    for key, value in filters.items():
        if key not in df.columns:
            raise ValueError(f"Unknown column: {key}")
        df = df[df[key] == value]

    return df


def get_best_runs(
    n: int = 10,
    metric: str = 'min_val_loss',
    ascending: bool = True,
    status: str = 'completed',
    path: Optional[Path] = None
) -> pd.DataFrame:
    """
    Get best performing runs by a metric.

    Args:
        n: Number of runs to return
        metric: Metric to sort by (default: min_val_loss)
        ascending: Sort order (True = lower is better, False = higher is better)
        status: Only include runs with this status (default: 'completed')
        path: Path to metadata file (optional)

    Returns:
        DataFrame with top N runs

    Examples:
        # Get 10 best runs by validation loss
        get_best_runs(n=10, metric='min_val_loss')

        # Get 5 best runs by R² score
        get_best_runs(n=5, metric='best_layer_r2', ascending=False)
    """
    df = load_metadata(path)

    # Filter by status if specified
    if status is not None:
        df = df[df['status'] == status]

    # Filter out null values for the metric
    df = df[df[metric].notna()]

    # Sort and return top N
    df = df.sort_values(metric, ascending=ascending)
    return df.head(n)


def get_sweep_summary(
    sweep_timestamp: Union[str, pd.Timestamp],
    path: Optional[Path] = None
) -> Dict:
    """
    Get summary statistics for a sweep.

    Args:
        sweep_timestamp: Timestamp identifying the sweep
        path: Path to metadata file (optional)

    Returns:
        Dictionary with sweep statistics

    Example:
        sweep_info = get_sweep_summary('2025-12-09 01:03:57')
        print(sweep_info['total_runs'])
        print(sweep_info['best_run_id'])
    """
    df = load_metadata(path)

    # Convert timestamp if string
    if isinstance(sweep_timestamp, str):
        sweep_timestamp = pd.to_datetime(sweep_timestamp)

    # Filter to sweep runs
    sweep_runs = df[df['sweep_timestamp'] == sweep_timestamp]

    if len(sweep_runs) == 0:
        return {
            'total_runs': 0,
            'error': f'No runs found for sweep {sweep_timestamp}'
        }

    # Get best run (by min_val_loss)
    completed = sweep_runs[sweep_runs['status'] == 'completed']
    best_run = None
    best_run_id = None

    if len(completed) > 0 and completed['min_val_loss'].notna().any():
        best_idx = completed['min_val_loss'].idxmin()
        best_run = completed.loc[best_idx]
        best_run_id = best_run['run_id']

    # Status breakdown
    status_counts = sweep_runs['status'].value_counts().to_dict()

    # Architecture parameter ranges
    arch_params = ['n_layer', 'n_embd', 'n_head', 'd_head', 'n_inner', 'n_ctx']
    param_ranges = {}
    for param in arch_params:
        if param in sweep_runs.columns and sweep_runs[param].notna().any():
            param_ranges[param] = {
                'min': sweep_runs[param].min(),
                'max': sweep_runs[param].max(),
                'unique_values': sweep_runs[param].nunique()
            }

    return {
        'sweep_timestamp': sweep_timestamp,
        'total_runs': len(sweep_runs),
        'status_breakdown': status_counts,
        'best_run_id': best_run_id,
        'best_val_loss': best_run['min_val_loss'] if best_run is not None else None,
        'parameter_ranges': param_ranges,
        'runs': sweep_runs
    }


def find_incomplete_runs(path: Optional[Path] = None) -> pd.DataFrame:
    """
    Find all incomplete or failed runs.

    Args:
        path: Path to metadata file (optional)

    Returns:
        DataFrame with incomplete/failed runs
    """
    df = load_metadata(path)
    return df[df['status'].isin(['incomplete', 'failed'])]


def get_architecture_stats(path: Optional[Path] = None) -> pd.DataFrame:
    """
    Get statistics grouped by architecture.

    Args:
        path: Path to metadata file (optional)

    Returns:
        DataFrame with architecture statistics
    """
    df = load_metadata(path)

    # Only completed runs with metrics
    completed = df[(df['status'] == 'completed') & (df['min_val_loss'].notna())]

    # Group by architecture parameters
    arch_cols = ['n_layer', 'n_embd', 'n_head', 'd_head', 'n_inner', 'n_ctx', 'attn_only']

    stats = completed.groupby(arch_cols, dropna=False).agg({
        'run_id': 'count',
        'min_val_loss': ['mean', 'std', 'min'],
        'param_count': 'first',
        'best_layer_r2': 'max'
    }).reset_index()

    # Flatten column names
    stats.columns = ['_'.join(col).strip('_') if col[1] else col[0]
                     for col in stats.columns.values]

    # Rename for clarity
    stats = stats.rename(columns={
        'run_id_count': 'num_runs',
        'min_val_loss_mean': 'avg_val_loss',
        'min_val_loss_std': 'std_val_loss',
        'min_val_loss_min': 'best_val_loss',
        'param_count_first': 'param_count',
        'best_layer_r2_max': 'best_r2'
    })

    return stats.sort_values('best_val_loss')


def list_sweeps(path: Optional[Path] = None) -> pd.DataFrame:
    """
    List all sweeps with summary statistics.

    Args:
        path: Path to metadata file (optional)

    Returns:
        DataFrame with one row per sweep
    """
    df = load_metadata(path)

    sweep_runs = df[df['is_sweep']]

    if len(sweep_runs) == 0:
        return pd.DataFrame()

    # Group by sweep
    sweeps = sweep_runs.groupby('sweep_timestamp').agg({
        'run_id': 'count',
        'status': lambda x: dict(x.value_counts()),
        'min_val_loss': 'min',
        'param_count': ['min', 'max'],
        'process': 'first'
    }).reset_index()

    # Flatten columns
    sweeps.columns = ['sweep_timestamp', 'total_runs', 'status_breakdown',
                      'best_val_loss', 'min_params', 'max_params', 'process']

    return sweeps.sort_values('sweep_timestamp', ascending=False)


def get_run_info(run_id: str, path: Optional[Path] = None) -> Dict:
    """
    Get detailed information for a specific run.

    Args:
        run_id: Run identifier
        path: Path to metadata file (optional)

    Returns:
        Dictionary with run information
    """
    df = load_metadata(path)

    run = df[df['run_id'] == run_id]

    if len(run) == 0:
        return {'error': f'Run not found: {run_id}'}

    return run.iloc[0].to_dict()


def compare_runs(
    run_ids: List[str],
    columns: Optional[List[str]] = None,
    path: Optional[Path] = None
) -> pd.DataFrame:
    """
    Compare multiple runs side-by-side.

    Args:
        run_ids: List of run identifiers
        columns: Columns to include (default: key metrics)
        path: Path to metadata file (optional)

    Returns:
        DataFrame with selected columns for comparison
    """
    df = load_metadata(path)

    # Filter to requested runs
    runs = df[df['run_id'].isin(run_ids)]

    if columns is None:
        # Default comparison columns
        columns = [
            'run_id', 'status', 'n_layer', 'n_embd', 'n_head', 'd_head',
            'n_inner', 'n_ctx', 'attn_only', 'param_count',
            'learning_rate', 'batch_size', 'min_val_loss',
            'best_layer_r2', 'final_llr_mean'
        ]

    return runs[columns].set_index('run_id')


if __name__ == "__main__":
    # Example usage
    print("Loading metadata...")
    df = load_metadata()

    print(f"\nTotal runs: {len(df)}")
    print(f"Completed: {(df['status'] == 'completed').sum()}")

    print("\n--- Top 5 runs by validation loss ---")
    best = get_best_runs(n=5)
    print(best[['run_id', 'n_layer', 'n_embd', 'param_count', 'min_val_loss']].to_string())

    print("\n--- All sweeps ---")
    sweeps = list_sweeps()
    print(sweeps[['sweep_timestamp', 'total_runs', 'best_val_loss']].head(10).to_string())

    print("\n--- Incomplete runs ---")
    incomplete = find_incomplete_runs()
    print(f"Total incomplete/failed: {len(incomplete)}")
